# permissions for end users to view pipelineruns.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pipelinerun-viewer-role
rules:
- apiGroups:
  - pipestudio.github.com
  resources:
  - pipelineruns
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pipestudio.github.com
  resources:
  - pipelineruns/status
  verbs:
  - get
