# permissions for end users to edit pipelineruns.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pipelinerun-editor-role
rules:
- apiGroups:
  - pipestudio.github.com
  resources:
  - pipelineruns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pipestudio.github.com
  resources:
  - pipelineruns/status
  verbs:
  - get
