## Append samples you want in your CSV to this file as resources ##
resources:
- pipestudio_v1alpha1_task.yaml
- pipestudio_v1alpha1_taskrun.yaml
- pipestudio_v1alpha1_pipelineresource.yaml
- pipestudio_v1alpha1_pipeline.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
