apiVersion: pipestudio.github.com/v1alpha1
kind: PipelineRun
metadata:
  name: pipelinerun-sample
spec:
  pipelineRef: 
    name: pipeline-sample
  serviceAccount: 'default'
  resources:
    - name: source-repo
      resourceRef: 
        name: go-example-git
