apiVersion: pipestudio.github.com/v1alpha1
kind: Pipeline
metadata:
  name: pipeline-sample
spec:
  resources:
    - name: source-repo
      type: git
  tasks:
    - name: readme
      taskRef: 
        name: read-task
      inputs:
        resources:
          - name: workspace
            resource: source-repo
        params:
          - name: filename
            value: Dockerfile