apiVersion: pipestudio.github.com/v1alpha1
kind: TaskRun
metadata:
  name: build-push
spec:
  taskRef:
    name: build-push
  trigger:
    type: manual
  serviceAccount: foo
  inputs:
    resources:
      - name: go-boilerplate
        resourceRef:
          name: go-example-git
    params:
      - name: dockerfileName
        value: go-boilerplate/Dockerfile
      - name: imageTag
        value: leandro21/pipe
      - name: workspace
        value: /workspace
