apiVersion: pipestudio.github.com/v1alpha1
kind: Task
metadata:
  name: task-sample
spec:
  # Add fields here
  steps: 
  - name: hello-world
    image: ubuntu
    command:
        - /bin/bash
    args:
        - "echo hello world"
