apiVersion: pipestudio.github.com/v1alpha1
kind: Task
metadata:
  name: read-task
spec:
  inputs:
    resources:
      - name: workspace
        type: git
  steps:
    - name: readme
      image: ubuntu
      command: ["/bin/bash"]
      args: ["-c", "cat Dockerfile"]
      workingDir: "/workspace/workspace"
