apiVersion: pipestudio.github.com/v1alpha1
kind: Task
metadata:
  name: read-task
spec:
  inputs:
    params:
      - name: filename
    resources:
      - name: workspace
        type: git
  steps:
    - name: readme
      image: ubuntu
      command: ["cat"]
      args:
        [
          "${inputs.params.filename}",
        ]
      workingDir: "/workspace/workspace"